const dotenv = require('dotenv')
dotenv.config()
module.exports = {
    SHIPPO_AUTH: process.env.SHIPPO_AUTH,
    TWILIO_FIRST_VAR: process.env.TWILIO_FIRST_VAR,
    TWILIO_SECOND_VAR: process.env.TWILIO_SECOND_VAR,
    GRAVITY_SANDBOX_OID: process.env.GRAVITY_SANDBOX_OID,
    GRAVITY_SANDBOX_AUTH_TOKEN: process.env.GRAVITY_SANDBOX_AUTH_TOKEN,
    GRAVITY_SANDBOX_ENVIRONMENT_URL: process.env.GRAVITY_SANDBOX_ENVIRONMENT_URL,
    GRAVITY_PROD_OID: process.env.GRAVITY_PROD_OID,
    GRAVITY_PROD_AUTH_TOKEN: process.env.GRAVITY_PROD_AUTH_TOKEN,
    GRAVITY_PROD_ENVIRONMENT_URL: process.env.GRAVITY_PROD_ENVIRONMENT_URL,
    MONGO_URL: process.env.MONGO_URL,
}